/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-11-14 02:27:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.client;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class client_005fjoin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/client/../base/footer.jsp", Long.valueOf(1699834313020L));
    _jspx_dependants.put("/WEB-INF/views/client/../base/header.jsp", Long.valueOf(1699834313020L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>client_login.jsp</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("      .client_login {\r\n");
      out.write("        max-width: 400px;\r\n");
      out.write("        margin: 0 auto;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        text-align: left;\r\n");
      out.write("      }\r\n");
      out.write("      .client_login > form {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("      }\r\n");
      out.write("      input[type=\"text\"],\r\n");
      out.write("      input[type=\"password\"],\r\n");
      out.write("      input[type=\"email\"],\r\n");
      out.write("      input[type=\"date\"] {\r\n");
      out.write("        height: 30px;\r\n");
      out.write("        margin: 4px 0 14px 0;\r\n");
      out.write("        border: 1px solid #ccc;\r\n");
      out.write("        border-radius: 3px;\r\n");
      out.write("        -webkit-appearance: none;\r\n");
      out.write("      }\r\n");
      out.write("      input[type=\"submit\"] {\r\n");
      out.write("        background: #333;\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        border: none;\r\n");
      out.write("        padding: 10px 20px;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        font-size: 13px;\r\n");
      out.write("      }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link href=\"resources/client/css/style.css\" rel=\"stylesheet\" />\r\n");
      out.write("</head>\r\n");
      out.write("<html>\r\n");
      out.write("<div id=\"container\" >\r\n");
      out.write("        <p>\r\n");
      out.write("            <h5>[ div : container ]</h5>\r\n");
      out.write("            <img src=\"resources/image/logo.png\" id=\"main_logo\">\r\n");
      out.write("            <h5 id=\"top_menu\"><a href=\"clientLogin.do\">LOGIN</a> | <a href=\"clientJoin.do\">JOIN</a> | <a href=\"clientCart.do\">CART</a></h5>\r\n");
      out.write("        </p>\r\n");
      out.write("<header id=\"header\">\r\n");
      out.write("	<h5>[ header : header ]</h5>\r\n");
      out.write("	<a href=\"mainIndex.do\"><img src=\"resources/image/logo_pull.png\" id=\"banner_logo\"></a>\r\n");
      out.write("\r\n");
      out.write("	<nav id=\"menubar\">\r\n");
      out.write("		<!--<h5>[ nav : menubar ]</h5>-->\r\n");
      out.write("		<ul>\r\n");
      out.write("			<!-- 새 창으로 열기 target=\"_blank\" -->\r\n");
      out.write("			<li><a href=\"productList.do?page=new\">New</a></li>\r\n");
      out.write("			<!-- product_new -->\r\n");
      out.write("			<li><a href=\"productList.do?page=weather\">Weather</a></li>\r\n");
      out.write("			<!-- product_weather -->\r\n");
      out.write("			<li><a href=\"productList.do?page=outer\">Outer</a></li>\r\n");
      out.write("			<!-- product_outer -->\r\n");
      out.write("			<li><a href=\"productList.do?page=top\">Top</a></li>\r\n");
      out.write("			<!-- product_top -->\r\n");
      out.write("			<li><a href=\"productList.do?page=dress\">Dress</a></li>\r\n");
      out.write("			<!-- product_dress -->\r\n");
      out.write("			<li><a href=\"productList.do?page=pants\">Pants</a></li>\r\n");
      out.write("			<!-- product_pants -->\r\n");
      out.write("			<li><a href=\"productList.do?page=skirts\">Skirts</a></li>\r\n");
      out.write("			<!-- product_skirts -->\r\n");
      out.write("		</ul>\r\n");
      out.write("	</nav>\r\n");
      out.write("</header>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<div class=\"client_login\">\r\n");
      out.write("		<h2>JoinUs</h2>\r\n");
      out.write("		<form action=\"#\" method=\"POST\">\r\n");
      out.write("			<label for=\"username\">아이디</label> \r\n");
      out.write("			<input type=\"text\" id=\"username\" name=\"username\" required /> \r\n");
      out.write("			<label for=\"password\">비밀번호</label> \r\n");
      out.write("			<input type=\"password\" id=\"password\" name=\"password\" required /> \r\n");
      out.write("			<label for=\"password-confirm\">비밀번호 재확인</label> \r\n");
      out.write("			<input type=\"password\" id=\"password-confirm\" name=\"password-confirm\" required /> \r\n");
      out.write("			<label for=\"name\">이름</label> \r\n");
      out.write("			<input type=\"text\" id=\"name\" name=\"name\" required /> \r\n");
      out.write("			<label for=\"birthdate\">생년월일</label> \r\n");
      out.write("			<input type=\"date\" id=\"birthdate\" name=\"birthdate\" required /> \r\n");
      out.write("			<label for=\"email\">이메일</label>\r\n");
      out.write("			<input type=\"email\" id=\"email\" name=\"email\" required /> \r\n");
      out.write("			<label for=\"address\">주소</label> \r\n");
      out.write("			<input type=\"text\" id=\"address\" name=\"address\" required /> \r\n");
      out.write("			<input type=\"submit\" value=\"가입하기\" />\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<footer>\r\n");
      out.write("\r\n");
      out.write("	<div id=\"footer\">\r\n");
      out.write("		<a href=\"login.mdo\"><img src=\"resources/image/logo_footer.png\" id=\"footer_logo\"></a>\r\n");
      out.write("		<h5>[ div : footer ]</h5>\r\n");
      out.write("		<div id=\"content\">\r\n");
      out.write("			<br>\r\n");
      out.write("			<!--// util menu -->\r\n");
      out.write("			<span class=\"addr\">서울특별시 종로구 돈화문로 26, 4층(묘동, 단성사)</span> \r\n");
      out.write("			<span class=\"rep\">대표 : 2조</span> \r\n");
      out.write("			<span class=\"tel\">전화 : 02-797-5036</span>\r\n");
      out.write("			<span class=\"rep\">사업자등록번호 : 111-1111-1111</span>\r\n");
      out.write("			<p class=\"copyright\">\r\n");
      out.write("				weatherWhere® is a Registered Trademark of	weatherWhere IP LLC. \r\n");
      out.write("				© 2023 weatherWhere IP LLC. All Rights	Reserved.\r\n");
      out.write("			</p>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</footer>\r\n");
      out.write("</div>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
